namespace: ocp-28021-istags


image_streams:
- external_image_name: docker.io/alpine
  internal_image_name: internal-alpine
  internal_image_tag: int
  external_image_tag: latest
  extra_tags:
  - name: tag1
    alias: false
  - name: tag2
    alias: true
- external_image_name: docker.io/alpine
  internal_image_name: internal-alpine
  internal_image_tag: 3.9
  external_image_tag: 3.9
  extra_tags:
  - name: tag3
    alias: false
  - name: latest
    alias: false
  - name: tag4
    alias: true



migration_sample_name: ocp-28021-istags
migration_plan_name: "{{ migration_sample_name }}-migplan-{{ ansible_date_time.epoch }}"
migration_name: "{{ migration_sample_name }}-mig-{{ ansible_date_time.epoch }}"
#migration_sample_files: "{{ playbook_dir }}/mig-controller/docs/scenarios/{{ migration_sample_name }}"
with_deploy: true
with_migrate: true
with_cleanup: true
with_validate: true
pv: false
quiesce: true
