- name: Cleanup resources
  include_role:
    name: migration_cleanup
  when: with_cleanup|bool

- name: Create bogus storageclasses in migration source cluster
  import_tasks: deploy_source.yml
  when: with_deploy|bool

- name: Create bogus storageclasses in migration target cluster 
  import_tasks: deploy_target.yml
  when: with_migrate|bool

- name: Validate source
  import_tasks: validate-source.yml
  when: (with_validate|bool) and (with_deploy|bool)

- name: Validate migration
  import_tasks: validate-target.yml
  when: (with_validate|bool) and (with_migrate|bool)

