namespace: "ocp-31309-quotanoattach"

storage_size: 1Mi
access_mode: ReadWriteOnce

migration_sample_name: "ocp-31309-quotanoattach"
migration_plan_name: "{{ migration_sample_name }}-migplan-{{ ansible_date_time.epoch }}"
migration_name: "{{ migration_sample_name }}-mig-{{ ansible_date_time.epoch }}"

with_deploy: true
with_migrate: true
with_cleanup: true
with_validate: true
pv: false
quiesce: false
