- name: check cronjob status in source cluster {{ migcluster_source_name }}
  k8s_facts:
    api_version: batch/v1beta1
    kind: CronJob 
    namespace: "{{ migration_sample_name }}"
  register:  cronjob_info 
  until: cronjob_info.resources | length > 0
  retries: 30
 
- debug:
    msg: "{{ cronjob_info }}"  

- name: sleep 1 minute to wait cron job to run
  shell: sleep 60

- name: Check app {{ cur_app_name }} pod status
  k8s_facts:
    api_version: v1 
    kind: Pod
    namespace: "{{ migration_sample_name }}"
    label_selectors: "cronowner={{ cur_app_name }}"
    field_selectors: 
    - status.phase=Succeeded
  register: pod
  until: pod.resources | length > 0
  retries: 30

- debug:
    msg: "{{ pod }}"

- name: get  the log of cron job
  #shell: oc logs $(oc get pod -n {{ migration_sample_name }}|grep Completed|tail -1|awk '{print $1}') -n {{ migration_sample_name }}
  shell: oc logs $(oc get pod -n {{ migration_sample_name }}|tail -1|awk '{print $1}') -n {{ migration_sample_name }}
  register: cronjob_log

- debug:
    msg: "{{ cronjob_log }}"

- name: set expected log string
  set_fact:
    expected_log_str: "Hello! from namespace {{ migration_sample_name }} while using image {{ cur_docker_image }}"

- name: check the log of cron job
  fail:
    msg: "the log of cron job is wrong"
  when: "expected_log_str not in cronjob_log.stdout"
